config/routes.rb
Rails.application.routes.draw do
  get "webs/index"

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :confirmations => 'users/confirmations',
    :unlocks => 'users/unlocks',
  }

  devise_scope :user do
    root :to => "users/sessions#new"
    get "signup", :to => "users/registrations#new"
    get "verify", :to => "users/registrations#verify"
    get "login", :to => "users/sessions#new"
    delete "logout", :to => "users/sessions#destroy"
  end

  resource :users, only: [:edit, :update] do
  collection do
    get "cart", :to => "shopping_carts#index"
    post "cart/create", :to => "shopping_carts#create"
    get "mypage/index", :to => "users#index"
    get "mypage", :to => "users#mypage"
    get "mypage/edit", :to => "users#edit"
    post "mypage", :to => "users#update"
    get "mypage/address/edit", :to => "users#edit_address"
    delete "cart", :to => "shopping_carts#destroy"
    put "mypage", :to => "users#update"
    get "users/mypage", :to => "users#mypage"
    get "mypage/edit_password", :to =>"users#edit_password"
    put "mypage/password", :to => "users#update_password"
    get  "mypage/favorite", :to => "users#favorite"
  end
end

  resources :products do
   member do
     get :favorite
   end
    resources :reviews, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews
  acts_as_likeable

  def reviews_new
    reviews.new
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user

  def save_review(review, review_params)
    review.content = review_params[:content]
    review.user_id = review_params[:user_id]
    review.product_id = review_params[:product_id]
    save
  end
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
  acts_as_shopping_cart

  scope :set_user_cart, -> (user) { user_cart = where(user_id: user.id, buy_flag: false)&.last
                           user_cart.nil? ? ShoppingCart.create(user_id: user.id)
                                  : user_cart }

  def tax_pct
    0
  end
end

app/models/shopping_cart_item.rb
class ShoppingCartItem < ApplicationRecord
  acts_as_shopping_cart_item
  scope :user_cart_items, -> (user_shoppingcart) { where(owner_id: user_shoppingcart) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :products, dependent: :destroy
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  acts_as_liker
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

    protected
      def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:account_update, keys: [:user_name])
        devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name])
      end

      private 
        def after_sign_in_path_for(resource)
          products_path
        end

        def after_sign_up_path_for(resource)
          products_path
        end
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :favorite]

  def index
    @products = Product.all
  end

  def show
    @reviews = @product.reviews
    @review = @reviews.new
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.save
    redirect_to product_url @product
  end

  def edit
  end

  def update
    @product.update(product_params)
    redirect_to product_url @product
  end

  def destroy
    @product.destroy
    redirect_to products_url
  end

  def favorite
    current_user.toggle_like!(@product)
    redirect_to product_url @product
  end

  private
    def product_params
      params.require(:product).permit(:name, :price, :quantity)
    end

    def set_product
      @product = Product.find(params[:id])
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    product = Product.find(params[:product_id])
    review = product.reviews_new
    review.save_review(review, review_params)
    redirect_to product_url(product)
  end

  private
   def review_params
     params.require(:review).permit(:content).
            merge(user_id: current_user.id, product_id: params[:product_id])
   end
end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
  before_action :set_cart, only: %i[index create destroy]
  def index
    @user_cart_items = ShoppingCartItem.user_cart_items(@user_cart)
  end

  def show
    @cart = ShoppingCart.find(user_id: current_user)
  end

  def create
    @product = Product.find(product_params[:product_id])
    @user_cart.add(@product, product_params[:price].to_i, product_params[:quantity].to_i)
    redirect_to cart_users_path
  end

  def update
  end

  def destroy
    @user_cart.buy_flag = true
    @user_cart.save
    redirect_to cart_users_url
  end

  private
   def product_params
     params.permit(:product_id, :price, :quantity)
   end

   def set_cart
     @user_cart = ShoppingCart.set_user_cart(current_user)
   end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user
  before_action :authenticate_user!

  def index
  end

  def show
    @user = User.find(current_user.id)
  end

  def edit
  end

  def update
    @user.update_without_current_password(user_params)
    redirect_to mypage_users_url
  end

  def mypage
  end

  def edit_address
  end

  def update_password
    if password_set?
      @user.update_password(user_params) 
      flash[:notice] = "パスワードは正しく更新されました。"
      redirect_to mypage_edit_password_users_url
    else
      @user.errors.add(:password, "パスワードに不備があります。")
      render "edit_password"
    end
  end

  def edit_password
  end

  def favorite
    @favorites = @user.likees(Product)
  end

   private
    def user_params
      params.require(:user).permit(:user_name)
    end

    def set_user
      @user = current_user
    end

    def password_set?
      user_params[:password].present? && user_params[:password_confirmation].present? ?
      true : false
    end
end

app/controllers/webs_controller.rb
class WebsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/shopping_carts_helper.rb
module ShoppingCartsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/webs_helper.rb
module WebsHelper
end

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>
<h1>Update Products</h1>

<%= form_with model: @product do |f| %>
  <%= f.text_field :name %>
  <%= f.number_field :price %>
  <%= f.submit "Update" %>
<% end %>

<%= link_to "Back", products_path %>

app/views/products/index.html.erb
<h1>Products#index</h1>
<p>Find me in app/views/products/index.html.erb</p>
<% @products.each do |product| %>
  <%= product.name %>
  <%= product.price %>
  <%= product.quantity %>
  <%= link_to "Show", product_path(product) %>
  <%= link_to "Edit", edit_product_path(product) %>
  <%= link_to 'product削除', product, data: { turbo_method: :delete , turbo_confirm: "productを削除しますか？" } %>
<% end %>

<p><%= link_to "New", new_product_path %></p>

app/views/products/new.html.erb
<h1>Products#new</h1>
<p>Find me in app/views/products/new.html.erb</p>
<%= form_with model: @product do |f| %>
  <p>名前</p>
  <%= f.text_field :name %>
  <p>価格</p>
  <%= f.number_field :price %>
  <%= f.submit "Create" %>
<% end %>

<%= link_to "Back", products_path %>

app/views/products/show.html.erb
<h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p>

<div class="d-flex justify-content-center">
  <div class="row w-75">
    <div class="col-5 offset-1">
      <!--<%= image_tag "/images/dummy.png", class: "w-100 img-fuild" %>-->
    </div>

    <div class="col">
      <div class="d-flex flex-column">
        <h1 class="">
          <%= @product.name %>
          <%= @product.price %>
          <%= @product.quantity %>
        </h1>
      </div>

      <% if user_signed_in? %>
        <%= form_with url: cart_create_users_path, local: true do |f| %>
          <%= f.hidden_field :product_id, value: @product.id %>
          <%= f.hidden_field :name, value: @product.name %>
          <%= f.hidden_field :price, value: @product.price %>
          <p>---------------------------------------------------------------</p>
          <div class="form-group row">
            <%= f.label "数量", class: "col-sm-2 col-form-label" %>
            <div class="col-sm-10">
              <%= f.number_field :quantity, min:1, value:1, class: "form-control w-25"%>
            </div>
          </div>
          <p>---------------------------------------------------------------</p>
          <div class="row">
            <div class="col-7">
              <%= f.submit "カートに追加", class: "btn samuraimart-submit-button w-100" do %>
                <i class="fas fa-shopping-cart"></i>
              <% end %>
            </div>
            <div class="col-5">
              <%= link_to favorite_product_path, class: "btn samuraimart-favorite-button text-favorite w-100" do %>
                <i class="fa fa-heart"></i><%= current_user.likes?(@product) ? "お気に入り解除" : "お気に入り" %>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>

    </div>

    <div class="offset-1 col-11">
      <hr class="w-100">
      <h3 class="float-left">カスタマーレビュー</h3>
    </div>

    <div class="offset-1 col-10">
     <!-- レビューを実装する箇所になります -->
     <div class="row">
       <% @reviews.each do |review| %>
       <div class="offset-md-5 col-md-5">
         <p class="h3"><%= review.content %></p>
         <label><%= review.created_at %></label>
       </div>
       <% end %>
     </div>

     <% if user_signed_in? %>
       <div class="row">
         <div class="offset-md-5 col-md-5">
           <%= form_with model: @review, url: product_reviews_path(@product) do |f| %>
             <%= f.text_area :content, class: "form-control m-2" %>
             <%= f.submit "レビューを追加" , class:"btn samuraimart-submit-button ml-2"%>
           <% end %>
         </div>
       </div>
     <% end %>
    </div>
  </div>
</div>

app/views/shopping_carts/index.html.erb
<h1>ShoppingCarts#index</h1>
<p>Find me in app/views/shopping_carts/index.html.erb</p>
<div class="container d-flex justify-content-center mt-3">
  <div class="w-75">
    <h1>ショッピングカート</h1>

    <div class="offset-8 col-4">
      <div class="row">
        <div class="col-6">
          <h2>数量</h2>
        </div>
        <div class="col-6">
          <h2>小計</h2>
        </div>
      </div>
    </div>

    <hr>

    <div class="row">
      <% @user_cart_items.each do |user_cart_item| %>
        <% product = Product.find(user_cart_item.item_id) %>
        <div class="col-md-2 mt-2">
          <%= link_to product_path(product) do %>
              <%= image_tag "/images/dummy.png", class: "img-fuild w-100" %>
          <% end %>
        </div>
        <div class="col-md-6 mt-4">
          <h3 class="mt-4"><%= product.name %></h3>
        </div>
        <div class="col-md-2">
          <h3 class="w-100 mt-4">数<%= user_cart_item.quantity %></h3>
        </div>
        <div class="col-md-2">
          <h3 class="w-100 mt-4">価格<%= user_cart_item.price_cents/ 100 %></h3>
        </div>
        <div class="col-md-2">
          <h3 class="w-100 mt-4">￥<%= user_cart_item.price_cents * user_cart_item.quantity / 100 %></h3>
        </div>
      <% end %>
    </div>

    <hr>

    <div class="offset-8 col-4">
      <div class="row">
        <div class="col-6">
          <h2>合計</h2>
        </div>

        <div class="col-6">
          <h2>￥<%= @user_cart.total.fractional / 100 %></h2>
        </div>

        <div class="col-12 d-flex justify-content-end">
          表示価格は税込みです
        </div>
      </div>
    </div>

   <%= form_with url: cart_users_path , method: :delete, class: "d-flex justify-content-end mt-3" do |f| %>
     <%= link_to "買い物を続ける", products_path, class: "btn samuraimart-favorite-button border-dark text-dark mr-3" %>
     <%= f.submit "購入を確定する", class: "btn samuraimart-submit-button" %>
   <% end %>
  </div>
</div>