config/routes.rb
Rails.application.routes.draw do
  get "webs/index"

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :confirmations => 'users/confirmations',
    :unlocks => 'users/unlocks',
  }

  devise_scope :user do
    root :to => "users/sessions#new"
    get "signup", :to => "users/registrations#new"
    get "verify", :to => "users/registrations#verify"
    get "login", :to => "users/sessions#new"
    delete "logout", :to => "users/sessions#destroy"
  end

  resource :users, only: [:edit, :update] do
  collection do
    get "cart", :to => "shopping_carts#index"
    post "cart/create", :to => "shopping_carts#create"
    get "mypage/index", :to => "users#index"
    get "mypage", :to => "users#mypage"
    get "mypage/edit", :to => "users#edit"
    post "mypage", :to => "users#update"
    get "mypage/address/edit", :to => "users#edit_address"
    delete "cart", :to => "shopping_carts#destroy"
    put "mypage", :to => "users#update"
    get "users/mypage", :to => "users#mypage"
    get "mypage/edit_password", :to =>"users#edit_password"
    put "mypage/password", :to => "users#update_password"
    get  "mypage/favorite", :to => "users#favorite"
  end
end

  resources :products do
   member do
     get :favorite
   end
    resources :reviews, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews
  acts_as_likeable

  def reviews_new
    reviews.new
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user

  def save_review(review, review_params)
    review.content = review_params[:content]
    review.user_id = review_params[:user_id]
    review.product_id = review_params[:product_id]
    save
  end
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
  acts_as_shopping_cart

  scope :set_user_cart, -> (user) { user_cart = where(user_id: user.id, buy_flag: false)&.last
                           user_cart.nil? ? ShoppingCart.create(user_id: user.id)
                                  : user_cart }

  def tax_pct
    0
  end
end

app/models/shopping_cart_item.rb
class ShoppingCartItem < ApplicationRecord
  acts_as_shopping_cart_item
  scope :user_cart_items, -> (user_shoppingcart) { where(owner_id: user_shoppingcart) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :products, dependent: :destroy
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  acts_as_liker
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

    protected
      def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:account_update, keys: [:user_name])
        devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name])
      end

      private 
        def after_sign_in_path_for(resource)
          products_path
        end

        def after_sign_up_path_for(resource)
          products_path
        end
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :favorite]

  def index
    @products = Product.all
  end

  def show
    @reviews = @product.reviews
    @review = @reviews.new
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.save
    redirect_to product_url @product
  end

  def edit
  end

  def update
    @product.update(product_params)
    redirect_to product_url @product
  end

  def destroy
    @product.destroy
    redirect_to products_url
  end

  def favorite
    current_user.toggle_like!(@product)
    redirect_to product_url @product
  end

  private
    def product_params
      params.require(:product).permit(:name, :price, :quantity)
    end

    def set_product
      @product = Product.find(params[:id])
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    product = Product.find(params[:product_id])
    review = product.reviews_new
    review.save_review(review, review_params)
    redirect_to product_url(product)
  end

  private
   def review_params
     params.require(:review).permit(:content).
            merge(user_id: current_user.id, product_id: params[:product_id])
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user
  before_action :authenticate_user!

  def index
  end

  def show
    @user = User.find(current_user.id)
  end

  def edit
  end

  def update
    @user.update_without_current_password(user_params)
    redirect_to mypage_users_url
  end

  def mypage
  end

  def edit_address
  end

  def update_password
    if password_set?
      @user.update_password(user_params) 
      flash[:notice] = "パスワードは正しく更新されました。"
      redirect_to mypage_edit_password_users_url
    else
      @user.errors.add(:password, "パスワードに不備があります。")
      render "edit_password"
    end
  end

  def edit_password
  end

  def favorite
    @favorites = @user.likees(Product)
  end

   private
    def user_params
      params.require(:user).permit(:user_name)
    end

    def set_user
      @user = current_user
    end

    def password_set?
      user_params[:password].present? && user_params[:password_confirmation].present? ?
      true : false
    end
end

app/controllers/webs_controller.rb
class WebsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/shopping_carts_helper.rb
module ShoppingCartsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/webs_helper.rb
module WebsHelper
end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm samuraimart-header-container">
    <%= image_tag "/logo.jpg" %>
    <form class="form-inline">
      <div class="form-group">
        <input class="form-control samuraimart-header-search-input">
      </div>
      <div class="input-group">
        <button type="submit" class="btn samuraimart-header-search-button"><i class="fas fa-search samuraimart-header-search-icon"></i></button>
      </div>
    </form>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Right Side Of Navbar -->
      <ul class="navbar-nav ml-auto mr-5 mt-2">
      <!-- user_signed_in? はユーザがログインしているか調べるdeviseのHelperメソッド -->
      <% if user_signed_in? %>
        <li class="nav-item mr-5">
          <%= link_to mypage_favorite_users_path, class: "nav-link" do %>
            <i class="far fa-heart">お気に入りにしたproduct</i>
          <% end %>
        </li>
       <li class="nav-item mr-5">
         <%= link_to cart_users_path, class: "nav-link" do %>
           <i class="fas fa-shopping-cart">カート</i>
         <% end %>
       </li>
       <li class="nav-item mr-5">
         <%= link_to destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: "ログアウトしますか？" }, class: "nav-link" do %>
           <label>ログアウト</label>
         <% end %>
       </li>
       <li class="nav-item mr-5">
         <%= link_to products_path, class: "nav-link" do %>
           <label>product一覧</label>
         <% end %>
       </li>
       <li class="nav-item mr-5">
         <%= link_to webs_index_path, class: "nav-link" do %>
           <label>WEB</label>
         <% end %>
       </li>
      <% else %>
        <li class="nav-item mr-5">
          <%= link_to new_user_registration_path, class: "nav-link" do %>
            <label>新規登録</label>
          <% end %>
        </li>
        <li class="nav-item mr-5">
          <%= link_to login_path, class: "nav-link" do %>
            <label>ログイン</label>
          <% end %>
        </li>
        <hr>
      <% end %>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Da" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/4957713640.js" crossorigin="anonymous"></script>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "turbo", type: "module" %>
  </head>

  <body>
    <h1>device機能（カラム追加）、fontawesome実装、お気に入り機能表示、カート機能実装</h1>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render partial: 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/webs/index.html.erb
<h1>Webs#index</h1>
<p>Find me in app/views/webs/index.html.erb</p>